### ISSUE TITLE
exception in l10n code during first page load after VM provisioning

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1054]
```
Error: EINVAL, Conversion not supported.
    at GettextDomain.parseHeaders (/home/app/node_modules/node-gettext/index.js:105:22)
    at GettextDomain.parseHeaders (/home/app/node_modules/node-gettext/index.js:131:21)
    at GettextDomain.handle_strings (/home/app/node_modules/node-gettext/index.js:73:14)
    at GettextDomain.load_tables (/home/app/node_modules/node-gettext/index.js:66:14)
    at new GettextDomain (/home/app/node_modules/node-gettext/index.js:25:14)
    at Gettext.addTextdomain (/home/app/node_modules/node-gettext/index.js:221:28)
    at Object.handle (/home/app/code/lib/i18n.js:117:29)
    at next (/home/app/node_modules/connect/lib/http.js:201:15)
    at Object.logger [as handle] (/home/app/node_modules/connect/lib/middleware/logger.js:155:5)
    at next (/home/app/node_modules/connect/lib/http.js:201:15)
```

Steps to reproduce:
1. provision a new vm
2. deploy code to it (seen with sha c0479ca)
3. load the main page 
4. witness above trace
5. notice it goes away after reload

This may be related to recent provisioning changes, haven't dug in.

**Comment by fetep** [comment]
this is also happening in stage, so we'll need to merge this fix.

**Comment by fetep** [comment]
stack trace:

2012-02-06 07:48:43.447595500 Error: EINVAL, Conversion not supported.
2012-02-06 07:48:43.447599500     at GettextDomain.parseHeaders (/opt/browserid/node_modules/node-gettext/index.js:105:22)
2012-02-06 07:48:43.447602500     at GettextDomain.parseHeaders (/opt/browserid/node_modules/node-gettext/index.js:131:21)
2012-02-06 07:48:43.447605500     at GettextDomain.handle_strings (/opt/browserid/node_modules/node-gettext/index.js:73:14)
2012-02-06 07:48:43.447608500     at GettextDomain.load_tables (/opt/browserid/node_modules/node-gettext/index.js:66:14)
2012-02-06 07:48:43.447676500     at new GettextDomain (/opt/browserid/node_modules/node-gettext/index.js:25:14)
2012-02-06 07:48:43.447679500     at Gettext.addTextdomain (/opt/browserid/node_modules/node-gettext/index.js:221:28)
2012-02-06 07:48:43.447681500     at Object.handle (/opt/browserid/lib/i18n.js:105:29)
2012-02-06 07:48:43.447683500     at next (/opt/browserid/node_modules/connect/lib/http.js:201:15)
2012-02-06 07:48:43.447702500     at Object.logger [as handle](/opt/browserid/node_modules/connect/lib/middleware/logger.js:155:5)
2012-02-06 07:48:43.447705500     at next (/opt/browserid/node_modules/connect/lib/http.js:201:15)

@ozten, this might explain why the .mo files aren't properly loaded

**Comment by ozten** [comment]
Looking now, headed into meeting, so it might take a while.

**Comment by ozten** [comment]
I reproduced on AWS, but was unable to reproduce on my locale dev environment.

I added proper CHARSET settings to db_LB as well as the templates pot files.

http://viewvc.svn.mozilla.org/vc?view=revision&revision=101188
http://viewvc.svn.mozilla.org/vc?view=revision&revision=101190

I tested the fix by deploying a second AWS instance and requesting a page. Looks fixed.

Please let me know if you see any issues after the next svn up, compile-mo.sh.

**Comment by fetep** [comment]
lgtm in stage, thanks!
