### ISSUE TITLE
load_gen crash during problems with load balancer in stage. 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1666]
There probably isn't much to go on here in figuring out how to prevent in the future. This issue is mostly just to document the issue, and see if it ever comes up again. I was running load_gen from one of the clientX boxes, and it had been running fine for ~20 hours. @fetep noted in irc that there was a problem with a load balancer in stage, and right at that time the load_gen terminated on the uncaught exception below. This is not the first time I have seen a load balancer throw problems at load_gen, but this is the only time it crashed. 

```
2012-05-30 10:32:40.478058500 error: (signin) Error: socket hang up
2012-05-30 10:32:40.478167500 error: (signin) Error: socket hang up
2012-05-30 10:32:40.478276500 error: (signin) can't verify: Error: socket hang up
2012-05-30 10:32:40.478375500 error: (signin) Error: socket hang up
2012-05-30 10:32:40.478470500 error: (signin) Error: socket hang up
2012-05-30 10:32:40.478579500 error: (signin) can't verify: Error: socket hang up
2012-05-30 10:32:40.478703500 error: (signup) can't certify key: Error: socket hang up
2012-05-30 10:32:40.478809500 error: (signin) Error: socket hang up
2012-05-30 10:32:42.086383500    23587.20        112142.44       321966.64       232 R, 69 S (4sp 0rs 4al 3rh 220sn 0iy 1cs)     (21 ERRORS!)
2012-05-30 10:32:42.109758500
2012-05-30 10:32:42.109919500 node.js:201
2012-05-30 10:32:42.110143500         throw e; // process.nextTick error, or 'error' event on first tick
2012-05-30 10:32:42.110223500               ^
2012-05-30 10:32:42.111349500 TypeError: Cannot call method 'emit' of null
2012-05-30 10:32:42.111350500     at CleartextStream.<anonymous> (http.js:1163:11)
2012-05-30 10:32:42.111351500     at CleartextStream.emit (events.js:67:17)
2012-05-30 10:32:42.111351500     at Socket.onerror (tls.js:1144:17)
2012-05-30 10:32:42.111352500     at Socket.emit (events.js:88:20)
2012-05-30 10:32:42.111352500     at Array.48 (net.js:301:14)
2012-05-30 10:32:42.111353500     at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by jrgm** [comment]
I'm going to close this issue now. Nothing obvious to do in the above, and reproducing this is unlikely.

**Comment by jrgm** [comment]
At 2012-05-31 09:51:30.625, this same stack and process exit happened again from client9 (which had been running for about 18 hours at that point). In this crash, there weren't any handled errors preceding the uncaught exception. (There may have been a load test of an unrelated service running in stage at the same time).

**Comment by jrgm** [comment]
actually, there was another load_gen running from client8 at the same time (2012-05-31 09:51:30), and it showed a spew of errors (ECONNREFUSED).

**Comment by jrgm** [comment]
I haven't seen this again in the past month. So closing. Probably better to process.on('uncaughtException', ...) and just log these transients until there's a pattern or a v0.8 build of node.
