### ISSUE TITLE
node-gettext blowup on first run in new language

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1947]
This only happens on the _first_ page load requiring translations on a particular server.  Any subsequent page load in any locale works fine.

When I first when to fonts.personatest.org using Dutch as my locale, I got the following:

```
Error: EINVAL, Conversion not supported.
    at GettextDomain.parseHeaders (/home/app/code/node_modules/node-gettext/index.js:105:22)
    at GettextDomain.parseHeaders (/home/app/code/node_modules/node-gettext/index.js:131:21)
    at GettextDomain.handle_strings (/home/app/code/node_modules/node-gettext/index.js:73:14)
    at GettextDomain.load_tables (/home/app/code/node_modules/node-gettext/index.js:66:14)
    at new GettextDomain (/home/app/code/node_modules/node-gettext/index.js:25:14)
    at Gettext.addTextdomain (/home/app/code/node_modules/node-gettext/index.js:221:28)
    at Object.handle (/home/app/code/lib/i18n.js:119:29)
    at next (/home/app/code/node_modules/connect/lib/http.js:201:15)
    at Object.logger [as handle] (/home/app/code/node_modules/connect/lib/middleware/logger.js:155:5)
    at next (/home/app/code/node_modules/connect/lib/http.js:201:15)
```

STR (I believe)
1) Set up a new ephemeral instance
2) Push current dev to instance
3) Set browser language to a supported translation
4) Browse to https://<instancename>.personatest.org
5) Watch the blowup.

**Comment by lloyd** [comment]
I'm all over this, this is an old friend.

**Comment by lloyd** [comment]
gettext is no longer in use, this specific error should never be seen.
