### ISSUE TITLE
scripts/check_assertion has jwcrypto require exception.

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2225]
Steps to Repro

1) checkout dev

2) run

```
./scripts/check_assertion eyJhbGciOiJEUzI1NiJ9.eyJwd...somereallylongstring...YtLzy2CUJpu4Qv66dHtwheB45T1Q
```

Actual:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'jwcrypto/utils'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/ozten/browserid/scripts/check_assertion:3:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
```

**Comment by ozten** [comment]
Workaround: Use latest jwcrypto directly:

```
git clone git://github.com/mozilla/jwcrypto.git
cd jwcrypto
./bin/check-assertion eyJhbGciOiJEUzI1NiJ9.eyJwd...6dHtwheB45T1Q
```

**Comment by jrgm** [comment]
Can't actually find scripts/check_assertion in current dev.

Altternatively, in dev branch current, `./node_modules/.bin/check-assertion ...` works too.

Closing.
