### ISSUE TITLE
run-all.js not finding test modules on ephemeral instances.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2736]
reset-password-test | vista_firefox_16 | module.js:340
reset-password-test | vista_firefox_16 | throw err;
reset-password-test | vista_firefox_16 | ^
reset-password-test | vista_firefox_16 | Error: Cannot find module 'code/automation-tests/tests/reset-password-test'
reset-password-test | vista_firefox_16 | at Function.Module._resolveFilename (module.js:338:15)
reset-password-test | vista_firefox_16 | at Function.Module._load (module.js:280:25)
reset-password-test | vista_firefox_16 | at Module.require (module.js:362:17)
reset-password-test | vista_firefox_16 | at require (module.js:378:17)
reset-password-test | vista_firefox_16 | at /home/app/code/automation-tests/node_modules/vows/bin/vows:567:19
reset-password-test | vista_firefox_16 | at Array.reduce (native)
reset-password-test | vista_firefox_16 | at importSuites (/home/app/code/automation-tests/node_modules/vows/bin/vows:560:18)
reset-password-test | vista_firefox_16 | at Object.<anonymous> (/home/app/code/automation-tests/node_modules/vows/bin/vows:290:15)
reset-password-test | vista_firefox_16 | at Module._compile (module.js:449:26)
reset-password-test | vista_firefox_16 | at Object.Module._extensions..js (module.js:467:10)

**Comment by shane-tomlinson** [comment]
This is now affecting change-password-test and cancel-account.
