### ISSUE TITLE
Malformed verifier request triggers exception and 500 error

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#3001]
We got these 6 requests this morning (not IP has been changed to 1.2.3.4 and email address has been changed to censored@censored.example.com) : 

```
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:54:06 -0800] "POST /verify HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.007243 req_s:0.389277 retries:0
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:52:13 -0800] "POST /verify HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.014860 req_s:0.316261 retries:0
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:53:51 -0800] "POST /verify HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.007036 req_s:0.423880 retries:0
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:57:01 -0800] "POST /verify?assertion=%22censored@censored.example.com%22&audience=%22dev018.aim.local:80%22 HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.015616 req_s:0.338093 retries:0
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:53:26 -0800] "POST /verify HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.014873 req_s:0.308912 retries:0
1.2.3.4 verifier.login.persona.org - [12/Feb/2013:09:56:40 -0800] "POST /verify?assertion=%22censored@censored.example.com%22&audience=%22dev018.aim.local:80%22 HTTP/1.1" 500 224 "-" "Mozilla/5.0 (X11; Linux i686; rv:10.0.11) Gecko/20100101 Firefox/10.0.11" "-" "ssl: -" node_s:0.005052 req_s:0.373084 retries:0
```

Which triggered these exceptions and 500 errors from the verifier : 

```
2013-02-12 09:53:26.595814500 SyntaxError: Unexpected token a
2013-02-12 09:53:26.595819500     at parse (native)
2013-02-12 09:53:26.595820500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:53:26.595824500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:53:26.595826500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:53:26.595828500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:53:26.595830500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:53:26.595945500     at TCP.onread (net.js:403:27)
2013-02-12 09:54:06.504597500 SyntaxError: Unexpected token a
2013-02-12 09:54:06.504601500     at parse (native)
2013-02-12 09:54:06.504603500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:54:06.504606500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:54:06.504608500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:54:06.504610500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:54:06.504613500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:54:06.532624500     at TCP.onread (net.js:403:27)
2013-02-12 09:57:01.860221500 SyntaxError: Unexpected token a
2013-02-12 09:57:01.860225500     at parse (native)
2013-02-12 09:57:01.860227500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:57:01.860230500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:57:01.860232500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:57:01.860234500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:57:01.860236500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:57:01.860339500     at TCP.onread (net.js:403:27)
2013-02-12 09:52:14.139702500 SyntaxError: Unexpected token a
2013-02-12 09:52:14.139706500     at parse (native)
2013-02-12 09:52:14.139708500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:52:14.139711500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:52:14.139713500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:52:14.139715500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:52:14.139718500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:52:14.139823500     at TCP.onread (net.js:403:27)
2013-02-12 09:53:52.195034500 SyntaxError: Unexpected token a
2013-02-12 09:53:52.195038500     at parse (native)
2013-02-12 09:53:52.195039500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:53:52.195043500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:53:52.195045500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:53:52.195047500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:53:52.195049500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:53:52.195162500     at TCP.onread (net.js:403:27)
2013-02-12 09:56:41.520522500 SyntaxError: Unexpected token a
2013-02-12 09:56:41.520527500     at parse (native)
2013-02-12 09:56:41.520528500     at IncomingMessage.module.exports (/opt/browserid/node_modules/connect/lib/middleware/bodyParser.js:69:15)
2013-02-12 09:56:41.520531500     at IncomingMessage.EventEmitter.emit (events.js:90:17)
2013-02-12 09:56:41.520534500     at IncomingMessage._emitEnd (http.js:366:10)
2013-02-12 09:56:41.520535500     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2013-02-12 09:56:41.520538500     at Socket.socket.ondata (http.js:1704:22)
2013-02-12 09:56:41.520600500     at TCP.onread (net.js:403:27)
```

This in turn triggered our monitoring of HTTP 500's on the verifiers.

Can this exception be caught and handled gracefully, not resulting in a 500?

**Comment by jrgm** [comment]
A naive gist for fun, but lacking tests - https://gist.github.com/jrgm/4942228. Existing tests do pass locally though.

**Comment by jrgm** [comment]
So, I have a branch somewhere that addresses this. But if we upgraded express/connect (no small task) the current versions already handle this as a bad request.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
