### ISSUE TITLE
intermittent failure with npm install running lockdown on jenkins box in dns.js

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3298]
This is likely a DNS issue with the jenkins box, but I thought I'd start the trail here.  It occurs on all configs but most frequently on Linux and Safari. I've seen this about 25% of the runs.  The work around is to do an incremental build, not a full clobber.
1. fire up a build on jenkins, but going on IRC and PM with 
   jenkins: build browserid.dev.osx_safari_5
   which executes:
   npm install
   cd automated-tests
   npm install
2. review console output:
   https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.osx_safari_5/343/console

npm http GET http://127.0.0.1:43226/htmlparser/1.7.6
events.js:71
        throw arguments[1]; // Unhandled 'error' event
Error: getaddrinfo ENOENT
    at errnoException (dns.js:31:11)
    at Object.onanswer [as oncomplete](dns.js:123:16)

**Comment by jrgm** [comment]
Two things to try:
1. Add `ulimit -n 4096` to the build script (docs say the EMFILE will show as ENOENT).
2. Out of curiosity, add `node -e 'dns = require("dns"); dns.lookup("github.com", function() { console.dir(arguments) })'` to the top of the build script to see if that ever fails in resolving.

**Comment by edwindotcom** [comment]
i grabbed the last 24 runs and we got this dns.js issue 9 times.  

```
Edwin@ewong-16235:~/github/edmoz/jenkins-cli/logs$ grep -B 7 -irn 'errnoException' identity.browserid.dev.win7_firefox_16.28* 
identity.browserid.dev.win7_firefox_16.2841.txt-68-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2841.txt-69-npm http GET http://127.0.0.1:36344/winston/0.6.2
identity.browserid.dev.win7_firefox_16.2841.txt-70-
identity.browserid.dev.win7_firefox_16.2841.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2841.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2841.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2841.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2841.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2843.txt-68-npm http GET http://127.0.0.1:47352/htmlparser/1.7.6
identity.browserid.dev.win7_firefox_16.2843.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2843.txt-70-
identity.browserid.dev.win7_firefox_16.2843.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2843.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2843.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2843.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2843.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2845.txt-68-npm http GET http://127.0.0.1:44025/which/1.0.5
identity.browserid.dev.win7_firefox_16.2845.txt-69-npm http GET http://127.0.0.1:44025/connect/1.7.2
identity.browserid.dev.win7_firefox_16.2845.txt-70-
identity.browserid.dev.win7_firefox_16.2845.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2845.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2845.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2845.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2845.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2850.txt-68-npm http GET http://127.0.0.1:36740/htmlparser/1.7.6
identity.browserid.dev.win7_firefox_16.2850.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2850.txt-70-
identity.browserid.dev.win7_firefox_16.2850.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2850.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2850.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2850.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2850.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2853.txt-68-npm http GET http://127.0.0.1:48833/htmlparser/1.7.6
identity.browserid.dev.win7_firefox_16.2853.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2853.txt-70-
identity.browserid.dev.win7_firefox_16.2853.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2853.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2853.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2853.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2853.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2854.txt-68-npm http GET http://127.0.0.1:42248/jshint/0.9.1
identity.browserid.dev.win7_firefox_16.2854.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2854.txt-70-
identity.browserid.dev.win7_firefox_16.2854.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2854.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2854.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2854.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2854.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2862.txt-68-npm http GET http://127.0.0.1:40404/htmlparser/1.7.6
identity.browserid.dev.win7_firefox_16.2862.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2862.txt-70-
identity.browserid.dev.win7_firefox_16.2862.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2862.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2862.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2862.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2862.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2863.txt-68-npm http GET http://127.0.0.1:54872/htmlparser/1.7.6
identity.browserid.dev.win7_firefox_16.2863.txt-69-npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
identity.browserid.dev.win7_firefox_16.2863.txt-70-
identity.browserid.dev.win7_firefox_16.2863.txt-71-events.js:71
identity.browserid.dev.win7_firefox_16.2863.txt-72-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2863.txt-73-                       ^
identity.browserid.dev.win7_firefox_16.2863.txt-74-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2863.txt:75:    at errnoException (dns.js:31:11)
--
identity.browserid.dev.win7_firefox_16.2864.txt-383-npm http GET http://127.0.0.1:53603/optimist/-/optimist-0.3.4.tgz
identity.browserid.dev.win7_firefox_16.2864.txt-384-npm http GET http://127.0.0.1:53603/jsxgettext/-/jsxgettext-0.0.4.tgz
identity.browserid.dev.win7_firefox_16.2864.txt-385-
identity.browserid.dev.win7_firefox_16.2864.txt-386-events.js:71
identity.browserid.dev.win7_firefox_16.2864.txt-387-        throw arguments[1]; // Unhandled 'error' event
identity.browserid.dev.win7_firefox_16.2864.txt-388-                       ^
identity.browserid.dev.win7_firefox_16.2864.txt-389-Error: getaddrinfo ENOENT
identity.browserid.dev.win7_firefox_16.2864.txt:390:    at errnoException (dns.js:31:11)
```

**Comment by edwindotcom** [comment]
dupe of https://github.com/mozilla/browserid/issues/3303
