### ISSUE TITLE
failing tests not noticed by vows

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3835]
So, here's a long snippet of stdout from a test run in my not-ready-yet metrics branch. TL;DR - lots of tests failing, yet vows says at the end:

```
1767 tests of 1767 passed, 0 failed.
· · · ✓ OK » 7 honored (58.754s)
```

What's up with that? I could swear there was a similar bug opened not long ago, but I can't find it.

Arghs.

``` bash
tests/unverified-email-test.js
·············verifier (72405): error: uncaughtException stack=[TypeError: Cannot set property 'os' of undefined,     at _.extend (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:638:19),     at Array.forEach (native),     at _.each._.forEach (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:76:11),     at Function._.extend (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:636:5),     at /Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js:39:11,     at Function._.each._.forEach (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:84:24),     at store (/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js:35:9),     at /Users/jhirsch/codez/github/mozilla-browserid/bin/verifier:171:7,     at ChildProcess.ComputeCluster._runWorkOnWorker.worker.job (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/compute-cluster/lib/compute-cluster.js:107:13),     at ChildProcess.g (events.js:192:14)], date=Mon Aug 26 2013 16:54:34 GMT-0700 (PDT), pid=72405, uid=502, gid=20, cwd=/Users/jhirsch/codez/github/mozilla-browserid, execPath=/usr/local/bin/node, version=v0.8.24, argv=[node, /Users/jhirsch/codez/github/mozilla-browserid/bin/verifier], rss=47218688, heapTotal=34190336, heapUsed=16427376, loadavg=[3.88427734375, 2.7783203125, 2.087890625], uptime=957608, trace=[column=19, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=_.extend, line=638, method=extend, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=11, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=_.each._.forEach, line=76, method=each._.forEach, native=false, column=5, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=Function._.extend, line=636, method=_.extend, native=false, column=11, file=/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js, function=null, line=39, method=null, native=false, column=24, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=84, method=_.each._.forEach, native=false, column=9, file=/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js, function=store, line=35, method=null, native=false, column=7, file=/Users/jhirsch/codez/github/mozilla-browserid/bin/verifier, function=null, line=171, method=null, native=false, column=13, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/compute-cluster/lib/compute-cluster.js, function=ChildProcess.ComputeCluster._runWorkOnWorker.worker.job, line=107, method=ComputeCluster._runWorkOnWorker.worker.job, native=false, column=14, file=events.js, function=ChildProcess.g, line=192, method=g, native=false]
verifier (72405): error: TypeError: Cannot set property 'os' of undefined
·verifier (72405): error: uncaughtException stack=[TypeError: Cannot set property 'os' of undefined,     at _.extend (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:638:19),     at Array.forEach (native),     at _.each._.forEach (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:76:11),     at Function._.extend (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:636:5),     at /Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js:39:11,     at Function._.each._.forEach (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js:84:24),     at store (/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js:35:9),     at /Users/jhirsch/codez/github/mozilla-browserid/bin/verifier:154:7,     at ChildProcess.ComputeCluster._runWorkOnWorker.worker.job (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/compute-cluster/lib/compute-cluster.js:107:13),     at ChildProcess.g (events.js:192:14)], date=Mon Aug 26 2013 16:54:34 GMT-0700 (PDT), pid=72405, uid=502, gid=20, cwd=/Users/jhirsch/codez/github/mozilla-browserid, execPath=/usr/local/bin/node, version=v0.8.24, argv=[node, /Users/jhirsch/codez/github/mozilla-browserid/bin/verifier], rss=47382528, heapTotal=34190336, heapUsed=17169048, loadavg=[3.88427734375, 2.7783203125, 2.087890625], uptime=957608, trace=[column=19, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=_.extend, line=638, method=extend, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=11, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=_.each._.forEach, line=76, method=each._.forEach, native=false, column=5, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=Function._.extend, line=636, method=_.extend, native=false, column=11, file=/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js, function=null, line=39, method=null, native=false, column=24, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=84, method=_.each._.forEach, native=false, column=9, file=/Users/jhirsch/codez/github/mozilla-browserid/lib/kpi.js, function=store, line=35, method=null, native=false, column=7, file=/Users/jhirsch/codez/github/mozilla-browserid/bin/verifier, function=null, line=154, method=null, native=false, column=13, file=/Users/jhirsch/codez/github/mozilla-browserid/node_modules/compute-cluster/lib/compute-cluster.js, function=ChildProcess.ComputeCluster._runWorkOnWorker.worker.job, line=107, method=ComputeCluster._runWorkOnWorker.worker.job, native=false, column=14, file=events.js, function=ChildProcess.g, line=192, method=g, native=false]
verifier (72405): error: TypeError: Cannot set property 'os' of undefined
······ 
✓ OK » 20 honored (14.266s)
tests/used-address-as-primary-test.js
·········· 
✓ OK » 10 honored (4.146s)
tests/verifier-test.js
···················✗···········✗··················✗··✗····································· 


  generating an assertion with new style leaving off the audience
    ✗ fails as you would expect
    SyntaxError: Unexpected token T
    at Object.parse (native)
    at Object.tests.leaving off the audience.fails as you would expect (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:322:25)
    at runTest (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:91:26)
    at EventEmitter.on.on.output.type (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:71:9)
    at EventEmitter.emit (events.js:126:20)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:38:39)
    at Object.env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:46:29)
    at IncomingMessage.exports.post.meth.request.on.cb (/Users/jhirsch/codez/github/mozilla-browserid/lib/wsapi_client.js:200:11)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:367:10)

  generating an assertion with old style leaving off the audience
    ✗ fails as you would expect
    SyntaxError: Unexpected token T
    at Object.parse (native)
    at Object.tests.leaving off the audience.fails as you would expect (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:322:25)
    at runTest (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:91:26)
    at EventEmitter.on.on.output.type (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:71:9)
    at EventEmitter.emit (events.js:126:20)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:38:39)
    at Object.env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:46:29)
    at IncomingMessage.exports.post.meth.request.on.cb (/Users/jhirsch/codez/github/mozilla-browserid/lib/wsapi_client.js:200:11)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:367:10)

  generating an assertion with new style and submitting without proper Content-Type headers
    ✗ fails with a helpful error message
    SyntaxError: Unexpected token T
    at Object.parse (native)
    at Object.tests.and submitting without proper Content-Type headers.fails with a helpful error message (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:528:25)
    at runTest (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:91:26)
    at EventEmitter.on.on.output.type (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:71:9)
    at EventEmitter.emit (events.js:126:20)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:38:39)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:46:29)
    at IncomingMessage.tests.and submitting without proper Content-Type headers.topic (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:519:15)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:367:10)

  generating an assertion with old style and submitting without proper Content-Type headers
    ✗ fails with a helpful error message
    SyntaxError: Unexpected token T
    at Object.parse (native)
    at Object.tests.and submitting without proper Content-Type headers.fails with a helpful error message (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:528:25)
    at runTest (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:91:26)
    at EventEmitter.on.on.output.type (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows.js:71:9)
    at EventEmitter.emit (events.js:126:20)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:38:39)
    at env.callback (/Users/jhirsch/codez/github/mozilla-browserid/node_modules/vows/lib/vows/context.js:46:29)
    at IncomingMessage.tests.and submitting without proper Content-Type headers.topic (/Users/jhirsch/codez/github/mozilla-browserid/tests/verifier-test.js:519:15)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:367:10)
✗ Errored » 87 honored ∙ 4 errored (7.229s)
>>> Now Running: Front end unit tests under PhantomJS
· · · · router (72492): info: forwarding request: /common/js/error-messages.js -> http://127.0.0.1:10010/common/js/error-messages.js
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
'waitFor()' finished in 53182ms.
Tests completed in 53080 milliseconds.
1767 tests of 1767 passed, 0 failed.
· · · ✓ OK » 7 honored (58.754s)
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by jrgm** [comment]
```
"What's up with that? I could swear there was a similar bug opened not long ago, but I can't find it."
```

I opened GH-3797 about QUnit not detect compile errors in tests, and you may be thinking of that one. (I'll be updating that issue in a bit).

However, you're confusing which output comes from which tool above. 
- vows output is like "Errored » 87 honored ∙ 4 errored (7.229s)" and those reflect failures
- QUnit output is the line that says "1767 tests of 1767 passed, 0 failed."

**Comment by jaredhirsch** [comment]
derp. closing, nice catch @jrgm
