### ISSUE TITLE
b2g: 2-3 gaia-ui-tests persona tests fail out of 100

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#4020]
@zacc repro'd this via jenkins on a device,  I also repro'd on desktopB2G
1. launch desktopB2G found here:
   http://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-central/
2. run gaiatest with this test with --repeat=100
   https://github.com/mozilla-b2g/gaia/blob/master/tests/python/gaia-ui-tests/gaiatest/tests/functional/persona/test_persona_app.py

actual: The trusted UI never launches around run 65.  I'll run again on device and catch the logcat.

```
ROUND 66
-------
TEST-START test_persona_app.py
test_persona_standard_sign_in (test_persona_app.TestPersonaStandard) ... ERROR

======================================================================
ERROR: None
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marionette_client-0.6.2-py2.7.egg/marionette/marionette_test.py", line 143, in run
    testMethod()
  File "/Users/Edwin/github/edmoz/gaia/tests/python/gaia-ui-tests/gaiatest/tests/functional/persona/test_persona_app.py", line 37, in test_persona_standard_sign_in
    moz_id.switch_to_frame()
  File "/Users/Edwin/github/edmoz/gaia/tests/python/gaia-ui-tests/gaiatest/apps/ui_tests/regions/persona.py", line 26, in switch_to_frame
    self.marionette.switch_to_frame(self.marionette.find_element(*self._frame_locator))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marionette_client-0.6.2-py2.7.egg/marionette/marionette.py", line 1100, in find_element
    response = self._send_message('findElement', 'value', **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marionette_client-0.6.2-py2.7.egg/marionette/marionette.py", line 577, in _send_message
    self._handle_error(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marionette_client-0.6.2-py2.7.egg/marionette/marionette.py", line 598, in _handle_error
    raise NoSuchElementException(message=message, status=status, stacktrace=stacktrace)
TEST-UNEXPECTED-FAIL | test_persona_app.py test_persona_app.TestPersonaStandard.test_persona_standard_sign_in | NoSuchElementException: Unable to locate element: iframe[src*="identity"]
----------------------------------------------------------------------
Ran 1 test in 163.878s

FAILED (errors=1)
```

**Comment by csuciu** [comment]
I've run test_persona_app.py with --repeat=100 on the latest desktopB2G and didn't get any failures. All rounds passed.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
