### ISSUE TITLE
I cannot build it - (version not found: nice-route53@0.3.5)

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/persona#4217]
Hi,
I cannot build persona. Am I doing something wrong? Do I need a specific nodejs/npm version?

``` bash
$npm install
> browserid@1.0.0-b2 preinstall /home/andrei/Dev/exsources/persona
> node ./scripts/lockdown

NPM Lockdown is here to check your dependencies!  Never fear!

> browserid@1.0.0-b2 preinstall /home/andrei/Dev/exsources/persona
> node ./scripts/lockdown

npm WARN package.json connect@1.7.2 No README data
npm WARN package.json connect-logger-statsd@0.0.1 bugs['name'] should probably be bugs['url'].
npm ERR! Error: version not found: nice-route53@0.3.5
npm ERR!     at /home/andrei/dotfiles/dotfiles_subtree/ndenv/versions/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/home/andrei/dotfiles/dotfiles_subtree/ndenv/versions/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.18.6-1-ARCH
npm ERR! command "/home/andrei/.ndenv/versions/v0.10.36/bin/node" "/home/andrei/.ndenv/versions/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/andrei/Dev/exsources/persona
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

npm ERR! browserid@1.0.0-b2 preinstall: `node ./scripts/lockdown`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browserid@1.0.0-b2 preinstall script.
npm ERR! This is most likely a problem with the browserid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls browserid
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.6-1-ARCH
npm ERR! command "/home/andrei/.ndenv/versions/v0.10.36/bin/node" "/home/andrei/.ndenv/versions/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/andrei/Dev/exsources/persona
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/andrei/Dev/exsources/persona/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jrgm** [comment]
That's a confusing error. But as a workaround in the short-term, just do `npm install nice-route53 && npm install` to complete the install. 

I need to review a fix for lockdown and then bump the version of nice-route53 that we use.

**Comment by andreicristianpetcu** [comment]
Nice! Thank you!
